package com.truthlens.backend.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity representing a revoked JWT token in TruthLens.
 *
 * <p>Mapped to the {@code revoked_tokens} table. When a user logs out, changes
 * their password, or an administrator revokes a session, the token's identifier
 * (the JWT {@code jti} claim or an equivalent short identifier) is stored here
 * so that the authentication filter can reject it on subsequent requests.</p>
 *
 * <p><strong>Security note:</strong> Only the <em>token identifier</em> (a short
 * unique string) is stored — never the full raw JWT string. This limits the
 * risk of token leakage from the database.</p>
 *
 * <p>Revocation records are retained until {@link #expiresAt}, after which they
 * may safely be removed by a scheduled cleanup job (a later operational stage).
 * A database index on {@link #tokenIdentifier} ensures fast lookup during
 * request authentication.</p>
 */
@Entity
@Table(name = "revoked_tokens")
public class RevokedToken {

    // -------------------------------------------------------------------------
    // Identity
    // -------------------------------------------------------------------------

    /** Surrogate primary key — UUID generated by the application layer. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    // -------------------------------------------------------------------------
    // Token identification
    // -------------------------------------------------------------------------

    /**
     * The unique identifier of the revoked token. This corresponds to the JWT
     * {@code jti} (JWT ID) claim or an equivalent identifier. A unique constraint
     * at the database level prevents duplicate revocation entries.
     *
     * <p><strong>Do not</strong> store the full JWT string here.</p>
     */
    @Column(name = "token_identifier", nullable = false, unique = true, length = 255)
    private String tokenIdentifier;

    // -------------------------------------------------------------------------
    // Relationships
    // -------------------------------------------------------------------------

    /**
     * The user whose token was revoked. Loaded lazily — typically the token
     * identifier alone is sufficient for revocation checks.
     * The database foreign key cascades deletes from users → revoked_tokens,
     * so removing a user also removes their revocation records.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    // -------------------------------------------------------------------------
    // Timestamps & reason
    // -------------------------------------------------------------------------

    /**
     * The UTC-offset timestamp when this token was issued to expire.
     * Revocation records with {@code expiresAt} in the past are candidates for
     * cleanup since expired tokens are inherently invalid regardless of
     * revocation status.
     */
    @Column(name = "expires_at", nullable = false)
    private OffsetDateTime expiresAt;

    /**
     * The UTC-offset timestamp at which the token was explicitly revoked.
     * Set at the time the revocation record is created.
     */
    @Column(name = "revoked_at", nullable = false)
    private OffsetDateTime revokedAt;

    /**
     * A short description of why the token was revoked. Representative values:
     * {@code LOGOUT}, {@code PASSWORD_RESET}, {@code ADMIN_REVOCATION}.
     * Not enforced as an enum at this stage to allow operational flexibility.
     */
    @Column(name = "reason", length = 100)
    private String reason;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** Required no-arg constructor for JPA. */
    protected RevokedToken() {
    }

    /**
     * Convenience constructor for creating a revocation record.
     *
     * @param tokenIdentifier the JWT {@code jti} or equivalent token identifier
     * @param user            the user who owned the token
     * @param expiresAt       when the original token was set to expire
     * @param revokedAt       when this revocation was recorded
     * @param reason          short reason string (e.g. {@code "LOGOUT"})
     */
    public RevokedToken(String tokenIdentifier, User user,
                        OffsetDateTime expiresAt, OffsetDateTime revokedAt,
                        String reason) {
        this.tokenIdentifier = tokenIdentifier;
        this.user = user;
        this.expiresAt = expiresAt;
        this.revokedAt = revokedAt;
        this.reason = reason;
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    public UUID getId() {
        return id;
    }

    public String getTokenIdentifier() {
        return tokenIdentifier;
    }

    public void setTokenIdentifier(String tokenIdentifier) {
        this.tokenIdentifier = tokenIdentifier;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public OffsetDateTime getExpiresAt() {
        return expiresAt;
    }

    public void setExpiresAt(OffsetDateTime expiresAt) {
        this.expiresAt = expiresAt;
    }

    public OffsetDateTime getRevokedAt() {
        return revokedAt;
    }

    public void setRevokedAt(OffsetDateTime revokedAt) {
        this.revokedAt = revokedAt;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    // -------------------------------------------------------------------------
    // equals / hashCode
    // -------------------------------------------------------------------------

    /**
     * Equality is based on the unique {@code tokenIdentifier} business key.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RevokedToken other)) return false;
        return tokenIdentifier != null && tokenIdentifier.equals(other.tokenIdentifier);
    }

    @Override
    public int hashCode() {
        return tokenIdentifier == null ? 0 : tokenIdentifier.hashCode();
    }

    @Override
    public String toString() {
        return "RevokedToken{id=" + id + ", tokenIdentifier='" + tokenIdentifier
                + "', reason='" + reason + "'}";
    }
}
