package com.truthlens.backend.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.util.UUID;

/**
 * JPA entity representing a system role in TruthLens.
 *
 * <p>Mapped to the {@code roles} table. The five permitted role names are
 * defined by {@link RoleName} and enforced by a unique constraint at both
 * the database and application level.</p>
 *
 * <p>Roles are seeded by the Flyway initial migration and are not created
 * at runtime. Registration logic will assign the {@code USER} role to new
 * accounts in a later authentication stage.</p>
 */
@Entity
@Table(name = "roles")
public class Role {

    // -------------------------------------------------------------------------
    // Identity
    // -------------------------------------------------------------------------

    /**
     * Surrogate primary key — UUID generated by the application layer.
     * Seed data in the Flyway migration uses stable, hardcoded UUIDs so that
     * the five predefined roles are reproducible across environments.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    // -------------------------------------------------------------------------
    // Fields
    // -------------------------------------------------------------------------

    /**
     * The role name. Stored as a {@code VARCHAR} in PostgreSQL for readability
     * and schema stability. A unique constraint on {@code name} is enforced
     * at the database level by the Flyway migration.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "name", nullable = false, unique = true, length = 50)
    private RoleName name;

    /**
     * Optional human-readable description of what this role entails.
     * May be {@code null} for system roles whose purpose is implied by their name.
     */
    @Column(name = "description", length = 255)
    private String description;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** Required no-arg constructor for JPA. */
    protected Role() {
    }

    /**
     * Convenience constructor for creating a role with a name and description.
     *
     * @param name        the role name (must not be {@code null})
     * @param description optional description
     */
    public Role(RoleName name, String description) {
        this.name = name;
        this.description = description;
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    public UUID getId() {
        return id;
    }

    public RoleName getName() {
        return name;
    }

    public void setName(RoleName name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    // -------------------------------------------------------------------------
    // equals / hashCode
    // -------------------------------------------------------------------------

    /**
     * Equality is based solely on the business key {@code name}, which is
     * unique across all roles. This avoids issues with proxy objects and
     * uninitialized {@code id} fields during the persistence lifecycle.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Role other)) return false;
        return name != null && name.equals(other.name);
    }

    @Override
    public int hashCode() {
        return name == null ? 0 : name.hashCode();
    }

    @Override
    public String toString() {
        return "Role{id=" + id + ", name=" + name + "}";
    }
}
