package com.truthlens.backend.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.OffsetDateTime;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

/**
 * JPA entity representing a registered user account in TruthLens.
 *
 * <p>
 * Mapped to the {@code users} table. The email address is the primary
 * authentication identifier and carries a unique constraint at the database
 * level. Passwords are stored exclusively as BCrypt hashes — no plaintext
 * field is provided.
 * </p>
 *
 * <p>
 * Roles are associated through the {@code user_roles} join table.
 * The relationship is {@link FetchType#LAZY} to avoid loading the role set on
 * every user load; callers that need roles must explicitly access the field
 * within a transaction.
 * </p>
 *
 * <p>
 * Timestamps use {@link OffsetDateTime} to preserve timezone information,
 * which maps to {@code TIMESTAMPTZ} in PostgreSQL. They are maintained by
 * {@link #onCreate()} and {@link #onUpdate()} lifecycle callbacks rather than
 * database triggers so that the application layer retains full control.
 * </p>
 */
@Entity
@Table(name = "users")
public class User {

    // -------------------------------------------------------------------------
    // Identity
    // -------------------------------------------------------------------------

    /**
     * Surrogate primary key — UUID generated by the JPA/UUID strategy.
     * Never exposed as an auto-increment integer.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    // -------------------------------------------------------------------------
    // Authentication fields
    // -------------------------------------------------------------------------

    /**
     * The user's email address. This is the unique authentication identifier.
     * A database-level unique index is created by the Flyway migration.
     */
    @Column(name = "email", nullable = false, unique = true, length = 100)
    private String email;

    /**
     * BCrypt hash of the user's password. Only the hash is stored — never the
     * plaintext password. BCrypt encoding is applied in the authentication
     * service (a later stage).
     */
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    // -------------------------------------------------------------------------
    // Profile fields
    // -------------------------------------------------------------------------

    /**
     * The user's display name. Optional at this stage; populated during
     * registration or profile update.
     */
    @Column(name = "full_name", length = 255)
    private String fullName;

    // -------------------------------------------------------------------------
    // Account lifecycle
    // -------------------------------------------------------------------------

    /**
     * Current status of the account. Defaults to
     * {@link AccountStatus#PENDING_VERIFICATION}
     * when a new user registers; transitions to {@link AccountStatus#ACTIVE} upon
     * email verification. Stored as a {@code VARCHAR} in PostgreSQL.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 30)
    private AccountStatus status = AccountStatus.PENDING_VERIFICATION;

    // -------------------------------------------------------------------------
    // Timestamps
    // -------------------------------------------------------------------------

    /**
     * The UTC-offset timestamp at which this account was created.
     * Set once on first persist by {@link #onCreate()} and never updated.
     * Maps to {@code TIMESTAMPTZ} in PostgreSQL.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * The UTC-offset timestamp of the most recent update to this record.
     * Refreshed on every update by {@link #onUpdate()}.
     * Maps to {@code TIMESTAMPTZ} in PostgreSQL.
     */
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    // -------------------------------------------------------------------------
    // Relationships
    // -------------------------------------------------------------------------

    /**
     * The roles granted to this user. Mapped through the {@code user_roles}
     * join table. Loaded lazily — callers must access this set inside a
     * transaction. Role assignment is managed by the authentication/admin
     * services in later stages.
     */
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "user_roles", joinColumns = @JoinColumn(name = "user_id"), inverseJoinColumns = @JoinColumn(name = "role_id"))
    private Set<Role> roles = new HashSet<>();

    // -------------------------------------------------------------------------
    // Lifecycle callbacks
    // -------------------------------------------------------------------------

    /**
     * Sets {@link #createdAt} and {@link #updatedAt} when the entity is first
     * persisted. Both timestamps receive the same value (the moment of creation).
     */
    @PrePersist
    protected void onCreate() {
        OffsetDateTime now = OffsetDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Refreshes {@link #updatedAt} whenever the entity is updated.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = OffsetDateTime.now();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** Required no-arg constructor for JPA. */
    protected User() {
    }

    /**
     * Convenience constructor for the minimal fields required to create a user.
     *
     * @param email        the user's email address (authentication identifier)
     * @param passwordHash BCrypt hash of the user's password
     * @param fullName     the user's display name (may be {@code null})
     */
    public User(String email, String passwordHash, String fullName) {
        this.email = email;
        this.passwordHash = passwordHash;
        this.fullName = fullName;
        // status defaults to PENDING_VERIFICATION via field initializer
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    public UUID getId() {
        return id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public AccountStatus getStatus() {
        return status;
    }

    public void setStatus(AccountStatus status) {
        this.status = status;
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Returns a <em>live</em> reference to the roles set.
     * Mutation of this set is intentional — role assignment is performed by
     * calling {@code user.getRoles().add(role)} within a transaction.
     * This set is loaded lazily and must be accessed inside an active transaction.
     */
    public Set<Role> getRoles() {
        return roles;
    }

    // -------------------------------------------------------------------------
    // equals / hashCode
    // -------------------------------------------------------------------------

    /**
     * Equality is based on {@code email}, the unique business key.
     * Roles are deliberately excluded to prevent deep traversal.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (!(o instanceof User other))
            return false;
        return email != null && email.equals(other.email);
    }

    @Override
    public int hashCode() {
        return email == null ? 0 : email.hashCode();
    }

    @Override
    public String toString() {
        return "User{id=" + id + ", email='" + email + "', status=" + status + "}";
    }
}
